// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnss.proto

#ifndef PROTOBUF_gnss_2eproto__INCLUDED
#define PROTOBUF_gnss_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace gnss_driver {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gnss_2eproto();
void protobuf_AssignDesc_gnss_2eproto();
void protobuf_ShutdownFile_gnss_2eproto();

class Gnss;
class RangeInfo;
class GnssRange;

enum Gnss_Type {
  Gnss_Type_INVALID = 0,
  Gnss_Type_PROPAGATED = 1,
  Gnss_Type_SINGLE = 2,
  Gnss_Type_PSRDIFF = 3,
  Gnss_Type_PPP = 4,
  Gnss_Type_RTK_FLOAT = 5,
  Gnss_Type_RTK_INTEGER = 6
};
bool Gnss_Type_IsValid(int value);
const Gnss_Type Gnss_Type_Type_MIN = Gnss_Type_INVALID;
const Gnss_Type Gnss_Type_Type_MAX = Gnss_Type_RTK_INTEGER;
const int Gnss_Type_Type_ARRAYSIZE = Gnss_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Gnss_Type_descriptor();
inline const ::std::string& Gnss_Type_Name(Gnss_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Gnss_Type_descriptor(), value);
}
inline bool Gnss_Type_Parse(
    const ::std::string& name, Gnss_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Gnss_Type>(
    Gnss_Type_descriptor(), name, value);
}
enum RangeInfo_Constellation {
  RangeInfo_Constellation_GPS = 0,
  RangeInfo_Constellation_GLONASS = 1,
  RangeInfo_Constellation_SBAS = 2,
  RangeInfo_Constellation_GALILEO = 3,
  RangeInfo_Constellation_BEIDOU = 4,
  RangeInfo_Constellation_QZSS = 5
};
bool RangeInfo_Constellation_IsValid(int value);
const RangeInfo_Constellation RangeInfo_Constellation_Constellation_MIN = RangeInfo_Constellation_GPS;
const RangeInfo_Constellation RangeInfo_Constellation_Constellation_MAX = RangeInfo_Constellation_QZSS;
const int RangeInfo_Constellation_Constellation_ARRAYSIZE = RangeInfo_Constellation_Constellation_MAX + 1;

const ::google::protobuf::EnumDescriptor* RangeInfo_Constellation_descriptor();
inline const ::std::string& RangeInfo_Constellation_Name(RangeInfo_Constellation value) {
  return ::google::protobuf::internal::NameOfEnum(
    RangeInfo_Constellation_descriptor(), value);
}
inline bool RangeInfo_Constellation_Parse(
    const ::std::string& name, RangeInfo_Constellation* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RangeInfo_Constellation>(
    RangeInfo_Constellation_descriptor(), name, value);
}
// ===================================================================

class Gnss : public ::google::protobuf::Message {
 public:
  Gnss();
  virtual ~Gnss();

  Gnss(const Gnss& from);

  inline Gnss& operator=(const Gnss& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Gnss& default_instance();

  void Swap(Gnss* other);

  // implements Message ----------------------------------------------

  Gnss* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Gnss& from);
  void MergeFrom(const Gnss& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Gnss_Type Type;
  static const Type INVALID = Gnss_Type_INVALID;
  static const Type PROPAGATED = Gnss_Type_PROPAGATED;
  static const Type SINGLE = Gnss_Type_SINGLE;
  static const Type PSRDIFF = Gnss_Type_PSRDIFF;
  static const Type PPP = Gnss_Type_PPP;
  static const Type RTK_FLOAT = Gnss_Type_RTK_FLOAT;
  static const Type RTK_INTEGER = Gnss_Type_RTK_INTEGER;
  static inline bool Type_IsValid(int value) {
    return Gnss_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Gnss_Type_Type_MIN;
  static const Type Type_MAX =
    Gnss_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Gnss_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Gnss_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Gnss_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Gnss_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .gnss_driver.pb.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::gnss_driver::pb::Header& header() const;
  inline ::gnss_driver::pb::Header* mutable_header();
  inline ::gnss_driver::pb::Header* release_header();
  inline void set_allocated_header(::gnss_driver::pb::Header* header);

  // optional double measurement_time = 2;
  inline bool has_measurement_time() const;
  inline void clear_measurement_time();
  static const int kMeasurementTimeFieldNumber = 2;
  inline double measurement_time() const;
  inline void set_measurement_time(double value);

  // optional float velocity_latency = 3 [default = 0];
  inline bool has_velocity_latency() const;
  inline void clear_velocity_latency();
  static const int kVelocityLatencyFieldNumber = 3;
  inline float velocity_latency() const;
  inline void set_velocity_latency(float value);

  // optional .gnss_driver.pb.PointLLH position = 4;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 4;
  inline const ::gnss_driver::pb::PointLLH& position() const;
  inline ::gnss_driver::pb::PointLLH* mutable_position();
  inline ::gnss_driver::pb::PointLLH* release_position();
  inline void set_allocated_position(::gnss_driver::pb::PointLLH* position);

  // optional .gnss_driver.pb.Point3D position_std_dev = 5;
  inline bool has_position_std_dev() const;
  inline void clear_position_std_dev();
  static const int kPositionStdDevFieldNumber = 5;
  inline const ::gnss_driver::pb::Point3D& position_std_dev() const;
  inline ::gnss_driver::pb::Point3D* mutable_position_std_dev();
  inline ::gnss_driver::pb::Point3D* release_position_std_dev();
  inline void set_allocated_position_std_dev(::gnss_driver::pb::Point3D* position_std_dev);

  // optional .gnss_driver.pb.Point3D linear_velocity = 6;
  inline bool has_linear_velocity() const;
  inline void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 6;
  inline const ::gnss_driver::pb::Point3D& linear_velocity() const;
  inline ::gnss_driver::pb::Point3D* mutable_linear_velocity();
  inline ::gnss_driver::pb::Point3D* release_linear_velocity();
  inline void set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity);

  // optional .gnss_driver.pb.Point3D linear_velocity_std_dev = 7;
  inline bool has_linear_velocity_std_dev() const;
  inline void clear_linear_velocity_std_dev();
  static const int kLinearVelocityStdDevFieldNumber = 7;
  inline const ::gnss_driver::pb::Point3D& linear_velocity_std_dev() const;
  inline ::gnss_driver::pb::Point3D* mutable_linear_velocity_std_dev();
  inline ::gnss_driver::pb::Point3D* release_linear_velocity_std_dev();
  inline void set_allocated_linear_velocity_std_dev(::gnss_driver::pb::Point3D* linear_velocity_std_dev);

  // optional int32 num_sats = 8;
  inline bool has_num_sats() const;
  inline void clear_num_sats();
  static const int kNumSatsFieldNumber = 8;
  inline ::google::protobuf::int32 num_sats() const;
  inline void set_num_sats(::google::protobuf::int32 value);

  // optional .gnss_driver.pb.Gnss.Type type = 9;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 9;
  inline ::gnss_driver::pb::Gnss_Type type() const;
  inline void set_type(::gnss_driver::pb::Gnss_Type value);

  // optional uint32 solution_status = 10;
  inline bool has_solution_status() const;
  inline void clear_solution_status();
  static const int kSolutionStatusFieldNumber = 10;
  inline ::google::protobuf::uint32 solution_status() const;
  inline void set_solution_status(::google::protobuf::uint32 value);

  // optional uint32 position_type = 11;
  inline bool has_position_type() const;
  inline void clear_position_type();
  static const int kPositionTypeFieldNumber = 11;
  inline ::google::protobuf::uint32 position_type() const;
  inline void set_position_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.Gnss)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_measurement_time();
  inline void clear_has_measurement_time();
  inline void set_has_velocity_latency();
  inline void clear_has_velocity_latency();
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_position_std_dev();
  inline void clear_has_position_std_dev();
  inline void set_has_linear_velocity();
  inline void clear_has_linear_velocity();
  inline void set_has_linear_velocity_std_dev();
  inline void clear_has_linear_velocity_std_dev();
  inline void set_has_num_sats();
  inline void clear_has_num_sats();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_solution_status();
  inline void clear_has_solution_status();
  inline void set_has_position_type();
  inline void clear_has_position_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::gnss_driver::pb::Header* header_;
  double measurement_time_;
  ::gnss_driver::pb::PointLLH* position_;
  ::gnss_driver::pb::Point3D* position_std_dev_;
  float velocity_latency_;
  ::google::protobuf::int32 num_sats_;
  ::gnss_driver::pb::Point3D* linear_velocity_;
  ::gnss_driver::pb::Point3D* linear_velocity_std_dev_;
  int type_;
  ::google::protobuf::uint32 solution_status_;
  ::google::protobuf::uint32 position_type_;
  friend void  protobuf_AddDesc_gnss_2eproto();
  friend void protobuf_AssignDesc_gnss_2eproto();
  friend void protobuf_ShutdownFile_gnss_2eproto();

  void InitAsDefaultInstance();
  static Gnss* default_instance_;
};
// -------------------------------------------------------------------

class RangeInfo : public ::google::protobuf::Message {
 public:
  RangeInfo();
  virtual ~RangeInfo();

  RangeInfo(const RangeInfo& from);

  inline RangeInfo& operator=(const RangeInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeInfo& default_instance();

  void Swap(RangeInfo* other);

  // implements Message ----------------------------------------------

  RangeInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RangeInfo& from);
  void MergeFrom(const RangeInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RangeInfo_Constellation Constellation;
  static const Constellation GPS = RangeInfo_Constellation_GPS;
  static const Constellation GLONASS = RangeInfo_Constellation_GLONASS;
  static const Constellation SBAS = RangeInfo_Constellation_SBAS;
  static const Constellation GALILEO = RangeInfo_Constellation_GALILEO;
  static const Constellation BEIDOU = RangeInfo_Constellation_BEIDOU;
  static const Constellation QZSS = RangeInfo_Constellation_QZSS;
  static inline bool Constellation_IsValid(int value) {
    return RangeInfo_Constellation_IsValid(value);
  }
  static const Constellation Constellation_MIN =
    RangeInfo_Constellation_Constellation_MIN;
  static const Constellation Constellation_MAX =
    RangeInfo_Constellation_Constellation_MAX;
  static const int Constellation_ARRAYSIZE =
    RangeInfo_Constellation_Constellation_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Constellation_descriptor() {
    return RangeInfo_Constellation_descriptor();
  }
  static inline const ::std::string& Constellation_Name(Constellation value) {
    return RangeInfo_Constellation_Name(value);
  }
  static inline bool Constellation_Parse(const ::std::string& name,
      Constellation* value) {
    return RangeInfo_Constellation_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .gnss_driver.pb.RangeInfo.Constellation constellation = 1 [default = GPS];
  inline bool has_constellation() const;
  inline void clear_constellation();
  static const int kConstellationFieldNumber = 1;
  inline ::gnss_driver::pb::RangeInfo_Constellation constellation() const;
  inline void set_constellation(::gnss_driver::pb::RangeInfo_Constellation value);

  // optional int32 prn = 2;
  inline bool has_prn() const;
  inline void clear_prn();
  static const int kPrnFieldNumber = 2;
  inline ::google::protobuf::int32 prn() const;
  inline void set_prn(::google::protobuf::int32 value);

  // optional fixed32 carrier_frequency = 3;
  inline bool has_carrier_frequency() const;
  inline void clear_carrier_frequency();
  static const int kCarrierFrequencyFieldNumber = 3;
  inline ::google::protobuf::uint32 carrier_frequency() const;
  inline void set_carrier_frequency(::google::protobuf::uint32 value);

  // optional double pseudorange = 4 [default = nan];
  inline bool has_pseudorange() const;
  inline void clear_pseudorange();
  static const int kPseudorangeFieldNumber = 4;
  inline double pseudorange() const;
  inline void set_pseudorange(double value);

  // optional float pseudorange_std_dev = 5 [default = nan];
  inline bool has_pseudorange_std_dev() const;
  inline void clear_pseudorange_std_dev();
  static const int kPseudorangeStdDevFieldNumber = 5;
  inline float pseudorange_std_dev() const;
  inline void set_pseudorange_std_dev(float value);

  // optional double carrier_phase = 6 [default = nan];
  inline bool has_carrier_phase() const;
  inline void clear_carrier_phase();
  static const int kCarrierPhaseFieldNumber = 6;
  inline double carrier_phase() const;
  inline void set_carrier_phase(double value);

  // optional float carrier_phase_std_dev = 7 [default = nan];
  inline bool has_carrier_phase_std_dev() const;
  inline void clear_carrier_phase_std_dev();
  static const int kCarrierPhaseStdDevFieldNumber = 7;
  inline float carrier_phase_std_dev() const;
  inline void set_carrier_phase_std_dev(float value);

  // optional float doppler = 8 [default = nan];
  inline bool has_doppler() const;
  inline void clear_doppler();
  static const int kDopplerFieldNumber = 8;
  inline float doppler() const;
  inline void set_doppler(float value);

  // optional float doppler_std_dev = 9 [default = nan];
  inline bool has_doppler_std_dev() const;
  inline void clear_doppler_std_dev();
  static const int kDopplerStdDevFieldNumber = 9;
  inline float doppler_std_dev() const;
  inline void set_doppler_std_dev(float value);

  // optional int32 cno = 10 [default = -1];
  inline bool has_cno() const;
  inline void clear_cno();
  static const int kCnoFieldNumber = 10;
  inline ::google::protobuf::int32 cno() const;
  inline void set_cno(::google::protobuf::int32 value);

  // optional int32 lock_time = 11 [default = -1];
  inline bool has_lock_time() const;
  inline void clear_lock_time();
  static const int kLockTimeFieldNumber = 11;
  inline ::google::protobuf::int32 lock_time() const;
  inline void set_lock_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.RangeInfo)
 private:
  inline void set_has_constellation();
  inline void clear_has_constellation();
  inline void set_has_prn();
  inline void clear_has_prn();
  inline void set_has_carrier_frequency();
  inline void clear_has_carrier_frequency();
  inline void set_has_pseudorange();
  inline void clear_has_pseudorange();
  inline void set_has_pseudorange_std_dev();
  inline void clear_has_pseudorange_std_dev();
  inline void set_has_carrier_phase();
  inline void clear_has_carrier_phase();
  inline void set_has_carrier_phase_std_dev();
  inline void clear_has_carrier_phase_std_dev();
  inline void set_has_doppler();
  inline void clear_has_doppler();
  inline void set_has_doppler_std_dev();
  inline void clear_has_doppler_std_dev();
  inline void set_has_cno();
  inline void clear_has_cno();
  inline void set_has_lock_time();
  inline void clear_has_lock_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int constellation_;
  ::google::protobuf::int32 prn_;
  double pseudorange_;
  ::google::protobuf::uint32 carrier_frequency_;
  float pseudorange_std_dev_;
  double carrier_phase_;
  float carrier_phase_std_dev_;
  float doppler_;
  float doppler_std_dev_;
  ::google::protobuf::int32 cno_;
  ::google::protobuf::int32 lock_time_;
  friend void  protobuf_AddDesc_gnss_2eproto();
  friend void protobuf_AssignDesc_gnss_2eproto();
  friend void protobuf_ShutdownFile_gnss_2eproto();

  void InitAsDefaultInstance();
  static RangeInfo* default_instance_;
};
// -------------------------------------------------------------------

class GnssRange : public ::google::protobuf::Message {
 public:
  GnssRange();
  virtual ~GnssRange();

  GnssRange(const GnssRange& from);

  inline GnssRange& operator=(const GnssRange& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GnssRange& default_instance();

  void Swap(GnssRange* other);

  // implements Message ----------------------------------------------

  GnssRange* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GnssRange& from);
  void MergeFrom(const GnssRange& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .gnss_driver.pb.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::gnss_driver::pb::Header& header() const;
  inline ::gnss_driver::pb::Header* mutable_header();
  inline ::gnss_driver::pb::Header* release_header();
  inline void set_allocated_header(::gnss_driver::pb::Header* header);

  // optional double measurement_time = 2;
  inline bool has_measurement_time() const;
  inline void clear_measurement_time();
  static const int kMeasurementTimeFieldNumber = 2;
  inline double measurement_time() const;
  inline void set_measurement_time(double value);

  // repeated .gnss_driver.pb.RangeInfo ranges = 3;
  inline int ranges_size() const;
  inline void clear_ranges();
  static const int kRangesFieldNumber = 3;
  inline const ::gnss_driver::pb::RangeInfo& ranges(int index) const;
  inline ::gnss_driver::pb::RangeInfo* mutable_ranges(int index);
  inline ::gnss_driver::pb::RangeInfo* add_ranges();
  inline const ::google::protobuf::RepeatedPtrField< ::gnss_driver::pb::RangeInfo >&
      ranges() const;
  inline ::google::protobuf::RepeatedPtrField< ::gnss_driver::pb::RangeInfo >*
      mutable_ranges();

  // @@protoc_insertion_point(class_scope:gnss_driver.pb.GnssRange)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_measurement_time();
  inline void clear_has_measurement_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::gnss_driver::pb::Header* header_;
  double measurement_time_;
  ::google::protobuf::RepeatedPtrField< ::gnss_driver::pb::RangeInfo > ranges_;
  friend void  protobuf_AddDesc_gnss_2eproto();
  friend void protobuf_AssignDesc_gnss_2eproto();
  friend void protobuf_ShutdownFile_gnss_2eproto();

  void InitAsDefaultInstance();
  static GnssRange* default_instance_;
};
// ===================================================================


// ===================================================================

// Gnss

// optional .gnss_driver.pb.Header header = 1;
inline bool Gnss::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Gnss::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Gnss::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Gnss::clear_header() {
  if (header_ != NULL) header_->::gnss_driver::pb::Header::Clear();
  clear_has_header();
}
inline const ::gnss_driver::pb::Header& Gnss::header() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::gnss_driver::pb::Header* Gnss::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::gnss_driver::pb::Header;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Gnss.header)
  return header_;
}
inline ::gnss_driver::pb::Header* Gnss::release_header() {
  clear_has_header();
  ::gnss_driver::pb::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void Gnss::set_allocated_header(::gnss_driver::pb::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Gnss.header)
}

// optional double measurement_time = 2;
inline bool Gnss::has_measurement_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Gnss::set_has_measurement_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Gnss::clear_has_measurement_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Gnss::clear_measurement_time() {
  measurement_time_ = 0;
  clear_has_measurement_time();
}
inline double Gnss::measurement_time() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.measurement_time)
  return measurement_time_;
}
inline void Gnss::set_measurement_time(double value) {
  set_has_measurement_time();
  measurement_time_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.measurement_time)
}

// optional float velocity_latency = 3 [default = 0];
inline bool Gnss::has_velocity_latency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Gnss::set_has_velocity_latency() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Gnss::clear_has_velocity_latency() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Gnss::clear_velocity_latency() {
  velocity_latency_ = 0;
  clear_has_velocity_latency();
}
inline float Gnss::velocity_latency() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.velocity_latency)
  return velocity_latency_;
}
inline void Gnss::set_velocity_latency(float value) {
  set_has_velocity_latency();
  velocity_latency_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.velocity_latency)
}

// optional .gnss_driver.pb.PointLLH position = 4;
inline bool Gnss::has_position() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Gnss::set_has_position() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Gnss::clear_has_position() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Gnss::clear_position() {
  if (position_ != NULL) position_->::gnss_driver::pb::PointLLH::Clear();
  clear_has_position();
}
inline const ::gnss_driver::pb::PointLLH& Gnss::position() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::gnss_driver::pb::PointLLH* Gnss::mutable_position() {
  set_has_position();
  if (position_ == NULL) position_ = new ::gnss_driver::pb::PointLLH;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Gnss.position)
  return position_;
}
inline ::gnss_driver::pb::PointLLH* Gnss::release_position() {
  clear_has_position();
  ::gnss_driver::pb::PointLLH* temp = position_;
  position_ = NULL;
  return temp;
}
inline void Gnss::set_allocated_position(::gnss_driver::pb::PointLLH* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Gnss.position)
}

// optional .gnss_driver.pb.Point3D position_std_dev = 5;
inline bool Gnss::has_position_std_dev() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Gnss::set_has_position_std_dev() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Gnss::clear_has_position_std_dev() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Gnss::clear_position_std_dev() {
  if (position_std_dev_ != NULL) position_std_dev_->::gnss_driver::pb::Point3D::Clear();
  clear_has_position_std_dev();
}
inline const ::gnss_driver::pb::Point3D& Gnss::position_std_dev() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.position_std_dev)
  return position_std_dev_ != NULL ? *position_std_dev_ : *default_instance_->position_std_dev_;
}
inline ::gnss_driver::pb::Point3D* Gnss::mutable_position_std_dev() {
  set_has_position_std_dev();
  if (position_std_dev_ == NULL) position_std_dev_ = new ::gnss_driver::pb::Point3D;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Gnss.position_std_dev)
  return position_std_dev_;
}
inline ::gnss_driver::pb::Point3D* Gnss::release_position_std_dev() {
  clear_has_position_std_dev();
  ::gnss_driver::pb::Point3D* temp = position_std_dev_;
  position_std_dev_ = NULL;
  return temp;
}
inline void Gnss::set_allocated_position_std_dev(::gnss_driver::pb::Point3D* position_std_dev) {
  delete position_std_dev_;
  position_std_dev_ = position_std_dev;
  if (position_std_dev) {
    set_has_position_std_dev();
  } else {
    clear_has_position_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Gnss.position_std_dev)
}

// optional .gnss_driver.pb.Point3D linear_velocity = 6;
inline bool Gnss::has_linear_velocity() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Gnss::set_has_linear_velocity() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Gnss::clear_has_linear_velocity() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Gnss::clear_linear_velocity() {
  if (linear_velocity_ != NULL) linear_velocity_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_velocity();
}
inline const ::gnss_driver::pb::Point3D& Gnss::linear_velocity() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.linear_velocity)
  return linear_velocity_ != NULL ? *linear_velocity_ : *default_instance_->linear_velocity_;
}
inline ::gnss_driver::pb::Point3D* Gnss::mutable_linear_velocity() {
  set_has_linear_velocity();
  if (linear_velocity_ == NULL) linear_velocity_ = new ::gnss_driver::pb::Point3D;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Gnss.linear_velocity)
  return linear_velocity_;
}
inline ::gnss_driver::pb::Point3D* Gnss::release_linear_velocity() {
  clear_has_linear_velocity();
  ::gnss_driver::pb::Point3D* temp = linear_velocity_;
  linear_velocity_ = NULL;
  return temp;
}
inline void Gnss::set_allocated_linear_velocity(::gnss_driver::pb::Point3D* linear_velocity) {
  delete linear_velocity_;
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    set_has_linear_velocity();
  } else {
    clear_has_linear_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Gnss.linear_velocity)
}

// optional .gnss_driver.pb.Point3D linear_velocity_std_dev = 7;
inline bool Gnss::has_linear_velocity_std_dev() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Gnss::set_has_linear_velocity_std_dev() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Gnss::clear_has_linear_velocity_std_dev() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Gnss::clear_linear_velocity_std_dev() {
  if (linear_velocity_std_dev_ != NULL) linear_velocity_std_dev_->::gnss_driver::pb::Point3D::Clear();
  clear_has_linear_velocity_std_dev();
}
inline const ::gnss_driver::pb::Point3D& Gnss::linear_velocity_std_dev() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.linear_velocity_std_dev)
  return linear_velocity_std_dev_ != NULL ? *linear_velocity_std_dev_ : *default_instance_->linear_velocity_std_dev_;
}
inline ::gnss_driver::pb::Point3D* Gnss::mutable_linear_velocity_std_dev() {
  set_has_linear_velocity_std_dev();
  if (linear_velocity_std_dev_ == NULL) linear_velocity_std_dev_ = new ::gnss_driver::pb::Point3D;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.Gnss.linear_velocity_std_dev)
  return linear_velocity_std_dev_;
}
inline ::gnss_driver::pb::Point3D* Gnss::release_linear_velocity_std_dev() {
  clear_has_linear_velocity_std_dev();
  ::gnss_driver::pb::Point3D* temp = linear_velocity_std_dev_;
  linear_velocity_std_dev_ = NULL;
  return temp;
}
inline void Gnss::set_allocated_linear_velocity_std_dev(::gnss_driver::pb::Point3D* linear_velocity_std_dev) {
  delete linear_velocity_std_dev_;
  linear_velocity_std_dev_ = linear_velocity_std_dev;
  if (linear_velocity_std_dev) {
    set_has_linear_velocity_std_dev();
  } else {
    clear_has_linear_velocity_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.Gnss.linear_velocity_std_dev)
}

// optional int32 num_sats = 8;
inline bool Gnss::has_num_sats() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Gnss::set_has_num_sats() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Gnss::clear_has_num_sats() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Gnss::clear_num_sats() {
  num_sats_ = 0;
  clear_has_num_sats();
}
inline ::google::protobuf::int32 Gnss::num_sats() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.num_sats)
  return num_sats_;
}
inline void Gnss::set_num_sats(::google::protobuf::int32 value) {
  set_has_num_sats();
  num_sats_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.num_sats)
}

// optional .gnss_driver.pb.Gnss.Type type = 9;
inline bool Gnss::has_type() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Gnss::set_has_type() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Gnss::clear_has_type() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Gnss::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::gnss_driver::pb::Gnss_Type Gnss::type() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.type)
  return static_cast< ::gnss_driver::pb::Gnss_Type >(type_);
}
inline void Gnss::set_type(::gnss_driver::pb::Gnss_Type value) {
  assert(::gnss_driver::pb::Gnss_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.type)
}

// optional uint32 solution_status = 10;
inline bool Gnss::has_solution_status() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Gnss::set_has_solution_status() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Gnss::clear_has_solution_status() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Gnss::clear_solution_status() {
  solution_status_ = 0u;
  clear_has_solution_status();
}
inline ::google::protobuf::uint32 Gnss::solution_status() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.solution_status)
  return solution_status_;
}
inline void Gnss::set_solution_status(::google::protobuf::uint32 value) {
  set_has_solution_status();
  solution_status_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.solution_status)
}

// optional uint32 position_type = 11;
inline bool Gnss::has_position_type() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Gnss::set_has_position_type() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Gnss::clear_has_position_type() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Gnss::clear_position_type() {
  position_type_ = 0u;
  clear_has_position_type();
}
inline ::google::protobuf::uint32 Gnss::position_type() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.Gnss.position_type)
  return position_type_;
}
inline void Gnss::set_position_type(::google::protobuf::uint32 value) {
  set_has_position_type();
  position_type_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.Gnss.position_type)
}

// -------------------------------------------------------------------

// RangeInfo

// optional .gnss_driver.pb.RangeInfo.Constellation constellation = 1 [default = GPS];
inline bool RangeInfo::has_constellation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RangeInfo::set_has_constellation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RangeInfo::clear_has_constellation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RangeInfo::clear_constellation() {
  constellation_ = 0;
  clear_has_constellation();
}
inline ::gnss_driver::pb::RangeInfo_Constellation RangeInfo::constellation() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.constellation)
  return static_cast< ::gnss_driver::pb::RangeInfo_Constellation >(constellation_);
}
inline void RangeInfo::set_constellation(::gnss_driver::pb::RangeInfo_Constellation value) {
  assert(::gnss_driver::pb::RangeInfo_Constellation_IsValid(value));
  set_has_constellation();
  constellation_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.constellation)
}

// optional int32 prn = 2;
inline bool RangeInfo::has_prn() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RangeInfo::set_has_prn() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RangeInfo::clear_has_prn() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RangeInfo::clear_prn() {
  prn_ = 0;
  clear_has_prn();
}
inline ::google::protobuf::int32 RangeInfo::prn() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.prn)
  return prn_;
}
inline void RangeInfo::set_prn(::google::protobuf::int32 value) {
  set_has_prn();
  prn_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.prn)
}

// optional fixed32 carrier_frequency = 3;
inline bool RangeInfo::has_carrier_frequency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RangeInfo::set_has_carrier_frequency() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RangeInfo::clear_has_carrier_frequency() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RangeInfo::clear_carrier_frequency() {
  carrier_frequency_ = 0u;
  clear_has_carrier_frequency();
}
inline ::google::protobuf::uint32 RangeInfo::carrier_frequency() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.carrier_frequency)
  return carrier_frequency_;
}
inline void RangeInfo::set_carrier_frequency(::google::protobuf::uint32 value) {
  set_has_carrier_frequency();
  carrier_frequency_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.carrier_frequency)
}

// optional double pseudorange = 4 [default = nan];
inline bool RangeInfo::has_pseudorange() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RangeInfo::set_has_pseudorange() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RangeInfo::clear_has_pseudorange() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RangeInfo::clear_pseudorange() {
  pseudorange_ = ::google::protobuf::internal::NaN();
  clear_has_pseudorange();
}
inline double RangeInfo::pseudorange() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.pseudorange)
  return pseudorange_;
}
inline void RangeInfo::set_pseudorange(double value) {
  set_has_pseudorange();
  pseudorange_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.pseudorange)
}

// optional float pseudorange_std_dev = 5 [default = nan];
inline bool RangeInfo::has_pseudorange_std_dev() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RangeInfo::set_has_pseudorange_std_dev() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RangeInfo::clear_has_pseudorange_std_dev() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RangeInfo::clear_pseudorange_std_dev() {
  pseudorange_std_dev_ = static_cast<float>(::google::protobuf::internal::NaN());
  clear_has_pseudorange_std_dev();
}
inline float RangeInfo::pseudorange_std_dev() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.pseudorange_std_dev)
  return pseudorange_std_dev_;
}
inline void RangeInfo::set_pseudorange_std_dev(float value) {
  set_has_pseudorange_std_dev();
  pseudorange_std_dev_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.pseudorange_std_dev)
}

// optional double carrier_phase = 6 [default = nan];
inline bool RangeInfo::has_carrier_phase() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RangeInfo::set_has_carrier_phase() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RangeInfo::clear_has_carrier_phase() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RangeInfo::clear_carrier_phase() {
  carrier_phase_ = ::google::protobuf::internal::NaN();
  clear_has_carrier_phase();
}
inline double RangeInfo::carrier_phase() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.carrier_phase)
  return carrier_phase_;
}
inline void RangeInfo::set_carrier_phase(double value) {
  set_has_carrier_phase();
  carrier_phase_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.carrier_phase)
}

// optional float carrier_phase_std_dev = 7 [default = nan];
inline bool RangeInfo::has_carrier_phase_std_dev() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RangeInfo::set_has_carrier_phase_std_dev() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RangeInfo::clear_has_carrier_phase_std_dev() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RangeInfo::clear_carrier_phase_std_dev() {
  carrier_phase_std_dev_ = static_cast<float>(::google::protobuf::internal::NaN());
  clear_has_carrier_phase_std_dev();
}
inline float RangeInfo::carrier_phase_std_dev() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.carrier_phase_std_dev)
  return carrier_phase_std_dev_;
}
inline void RangeInfo::set_carrier_phase_std_dev(float value) {
  set_has_carrier_phase_std_dev();
  carrier_phase_std_dev_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.carrier_phase_std_dev)
}

// optional float doppler = 8 [default = nan];
inline bool RangeInfo::has_doppler() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RangeInfo::set_has_doppler() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RangeInfo::clear_has_doppler() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RangeInfo::clear_doppler() {
  doppler_ = static_cast<float>(::google::protobuf::internal::NaN());
  clear_has_doppler();
}
inline float RangeInfo::doppler() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.doppler)
  return doppler_;
}
inline void RangeInfo::set_doppler(float value) {
  set_has_doppler();
  doppler_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.doppler)
}

// optional float doppler_std_dev = 9 [default = nan];
inline bool RangeInfo::has_doppler_std_dev() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RangeInfo::set_has_doppler_std_dev() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RangeInfo::clear_has_doppler_std_dev() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RangeInfo::clear_doppler_std_dev() {
  doppler_std_dev_ = static_cast<float>(::google::protobuf::internal::NaN());
  clear_has_doppler_std_dev();
}
inline float RangeInfo::doppler_std_dev() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.doppler_std_dev)
  return doppler_std_dev_;
}
inline void RangeInfo::set_doppler_std_dev(float value) {
  set_has_doppler_std_dev();
  doppler_std_dev_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.doppler_std_dev)
}

// optional int32 cno = 10 [default = -1];
inline bool RangeInfo::has_cno() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RangeInfo::set_has_cno() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RangeInfo::clear_has_cno() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RangeInfo::clear_cno() {
  cno_ = -1;
  clear_has_cno();
}
inline ::google::protobuf::int32 RangeInfo::cno() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.cno)
  return cno_;
}
inline void RangeInfo::set_cno(::google::protobuf::int32 value) {
  set_has_cno();
  cno_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.cno)
}

// optional int32 lock_time = 11 [default = -1];
inline bool RangeInfo::has_lock_time() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RangeInfo::set_has_lock_time() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RangeInfo::clear_has_lock_time() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RangeInfo::clear_lock_time() {
  lock_time_ = -1;
  clear_has_lock_time();
}
inline ::google::protobuf::int32 RangeInfo::lock_time() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.RangeInfo.lock_time)
  return lock_time_;
}
inline void RangeInfo::set_lock_time(::google::protobuf::int32 value) {
  set_has_lock_time();
  lock_time_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.RangeInfo.lock_time)
}

// -------------------------------------------------------------------

// GnssRange

// optional .gnss_driver.pb.Header header = 1;
inline bool GnssRange::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GnssRange::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GnssRange::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GnssRange::clear_header() {
  if (header_ != NULL) header_->::gnss_driver::pb::Header::Clear();
  clear_has_header();
}
inline const ::gnss_driver::pb::Header& GnssRange::header() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.GnssRange.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::gnss_driver::pb::Header* GnssRange::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::gnss_driver::pb::Header;
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.GnssRange.header)
  return header_;
}
inline ::gnss_driver::pb::Header* GnssRange::release_header() {
  clear_has_header();
  ::gnss_driver::pb::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void GnssRange::set_allocated_header(::gnss_driver::pb::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:gnss_driver.pb.GnssRange.header)
}

// optional double measurement_time = 2;
inline bool GnssRange::has_measurement_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GnssRange::set_has_measurement_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GnssRange::clear_has_measurement_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GnssRange::clear_measurement_time() {
  measurement_time_ = 0;
  clear_has_measurement_time();
}
inline double GnssRange::measurement_time() const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.GnssRange.measurement_time)
  return measurement_time_;
}
inline void GnssRange::set_measurement_time(double value) {
  set_has_measurement_time();
  measurement_time_ = value;
  // @@protoc_insertion_point(field_set:gnss_driver.pb.GnssRange.measurement_time)
}

// repeated .gnss_driver.pb.RangeInfo ranges = 3;
inline int GnssRange::ranges_size() const {
  return ranges_.size();
}
inline void GnssRange::clear_ranges() {
  ranges_.Clear();
}
inline const ::gnss_driver::pb::RangeInfo& GnssRange::ranges(int index) const {
  // @@protoc_insertion_point(field_get:gnss_driver.pb.GnssRange.ranges)
  return ranges_.Get(index);
}
inline ::gnss_driver::pb::RangeInfo* GnssRange::mutable_ranges(int index) {
  // @@protoc_insertion_point(field_mutable:gnss_driver.pb.GnssRange.ranges)
  return ranges_.Mutable(index);
}
inline ::gnss_driver::pb::RangeInfo* GnssRange::add_ranges() {
  // @@protoc_insertion_point(field_add:gnss_driver.pb.GnssRange.ranges)
  return ranges_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gnss_driver::pb::RangeInfo >&
GnssRange::ranges() const {
  // @@protoc_insertion_point(field_list:gnss_driver.pb.GnssRange.ranges)
  return ranges_;
}
inline ::google::protobuf::RepeatedPtrField< ::gnss_driver::pb::RangeInfo >*
GnssRange::mutable_ranges() {
  // @@protoc_insertion_point(field_mutable_list:gnss_driver.pb.GnssRange.ranges)
  return &ranges_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gnss_driver

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::gnss_driver::pb::Gnss_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gnss_driver::pb::Gnss_Type>() {
  return ::gnss_driver::pb::Gnss_Type_descriptor();
}
template <> struct is_proto_enum< ::gnss_driver::pb::RangeInfo_Constellation> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gnss_driver::pb::RangeInfo_Constellation>() {
  return ::gnss_driver::pb::RangeInfo_Constellation_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gnss_2eproto__INCLUDED
